name: Code CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  ubuntu-18_04:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:

    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Build local v
      run: make && sudo ./v symlink

    - name: Checkout jni
      uses: actions/checkout@v2
      with:
        path: jni

    - name: Link local jni folder in ~/.vmodules/jni
      run: |
        cd jni
        mkdir -p ~/.vmodules
        ln -s $(pwd) ~/.vmodules/jni
    - name: Test code formatting
      run: |
        cd jni
        v test-fmt

    - name: Run jni tests
      run: |
        cd jni
        v test .

    - name: Install and run V jni examples
      run: |
        cd jni
        JNI_HOME=$(pwd)
        export JAVA_HOME=$JAVA_HOME_11_X64
        # Test basic shell operation
        cd $JNI_HOME/examples/desktop/v_as_library
        export LD_LIBRARY_PATH=$(pwd):.
        v -cc gcc -cg  -shared libvlang.v
        javac io/vlang/V.java
        java io.vlang.V
        # Test build_and_run.vsh
        cd $JNI_HOME/examples/desktop/simple
        v run ./build_and_run.vsh
